name: test-all
on:
  push:
    branches-ignore:
      - 'dependabot/**' #avoid duplicates: only run the PR, not the commit
      - 'gh-pages' #github pages do not trigger all tests
    tags-ignore:
      - 'v*' #avoid rerun existing commit on release
  pull_request:
    branches:
      - 'main'

env:
  TEST_POSTGRES_PWD: ${RANDOM}${RANDOM}${RANDOM}
  #sqlserver must comply with password requirements (upper, lower, digit, symbol)
  TEST_SQLSERVER_PWD: ${RANDOM}Ax.${RANDOM}${RANDOM}
  TEST_ORACLE_PWD: ${RANDOM}${RANDOM}${RANDOM}
  TEST_SQLITE_PWD: ""
  TEST_H2_PWD: ""

jobs:
  test-java:
    runs-on: ubuntu-latest
    #if: ${{ false }}  # disable for now
    strategy:
      matrix:
        scope: [Sqlserver]
      fail-fast: false
      
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '8'
          cache: 'maven'

      # Starts the DBMS containers when applicable
      - name: Launch Postgres
        if: ${{ matrix.scope == 'Postgres' }}
        run: |
          docker run -d -p 5432:5432 --name test-postgres  --restart unless-stopped \
            -e POSTGRES_PASSWORD="$TEST_POSTGRES_PWD" \
            -e TEST_POSTGRES_PWD="$TEST_POSTGRES_PWD" \
            -v ${GITHUB_WORKSPACE}/setup/postgres:/docker-entrypoint-initdb.d \
            postgres:14
          chmod u+x setup/wait-container-ready.sh && ./setup/wait-container-ready.sh test-postgres "END SETUP!"

      - name: Launch Sqlserver
        if: ${{ matrix.scope == 'Sqlserver' }}
        run: |
          docker stop test-sqlserver && docker rm test-sqlserver
          docker run -d -p 1433:1433 --name test-sqlserver  --restart unless-stopped \
            -e SA_PASSWORD="$TEST_SQLSERVER_PWD" \
            -e TEST_SQLSERVER_PWD="$TEST_SQLSERVER_PWD" \
            -e "ACCEPT_EULA=Y" -e "MSSQL_PID=Developer" \
            -v ${GITHUB_WORKSPACE}/setup/sqlserver:/setup.d \
            mcr.microsoft.com/mssql/server:2017-latest
          chmod u+x setup/wait-container-ready.sh && ./setup/wait-container-ready.sh test-sqlserver "SQL Server is now ready for client connections"
          # SQLServer does not have an on startup script, run it now
          docker exec test-sqlserver bash -c "chmod u+x setup.d/sqlserver-setup.sh && ./setup.d/sqlserver-setup.sh"     
      
      - name: Launch Oracle
        if: ${{ matrix.scope == 'Oracle' }}
        run: |
          docker run -d -p 1521:1521 --name test-oracle  --restart unless-stopped \
            -e ORACLE_PASSWORD=$TEST_ORACLE_PWD \
            -e TEST_ORACLE_PWD="$TEST_ORACLE_PWD" \
            -v ${GITHUB_WORKSPACE}/setup/oracle:/container-entrypoint-initdb.d \
            gvenzl/oracle-xe:11.2.0.2-slim-faststart
          chmod u+x setup/wait-container-ready.sh && ./setup/wait-container-ready.sh test-oracle "DATABASE IS READY TO USE!"

      # Run the tests UT, IT and those that require database server
      
      - name: Test and aggregate surefire report - ${{ matrix.scope }}
        if: ${{ matrix.scope == 'UT' }}
        run: >
          mvn test surefire-report:report -Daggregate=true -Dsurefire.failIfNoSpecifiedTests=false
          -Dtest=!TestPostgres*,!TestSqlserver*,!TestOracle*,!ITTest*
          -Dsurefire.failIfNoSpecifiedTests=false
          -Dmaven.test.failure.ignore=true -U --no-transfer-progress

      - name: Test and aggregate surefire report - ${{ matrix.scope }}
        if: ${{ matrix.scope != 'UT' && matrix.scope != 'IT' }}
        run: >
          mvn test surefire-report:report -Daggregate=true -Dsurefire.failIfNoSpecifiedTests=false
          -Dtest=Test${{ matrix.scope }}*
          -Dmaven.test.failure.ignore=true -U --no-transfer-progress
          -Duser.timezone=Europe/Madrid
        # NOTE: must specify a timezone to avoid oracle error ORA-01882: timezone region not found

      # it requires first running the tests outside of maven, then a test case compares results
      - name: Test execution - ${{ matrix.scope }}
        if: ${{ matrix.scope == 'IT' }}
        run: |
          cd it
          ant install
          ant spring-petclinic
          ant qacover-api
          cd ..
          mvn install -P uber -pl qacover-core -DskipTests=true -DskipITs=true -Dmaven.javadoc.skip=true
          cd it
          ant qacover-uber 
      - name: Test results compraison - ${{ matrix.scope }}
        if: ${{ matrix.scope == 'IT' }}
        run: >
          mvn verify surefire-report:report -Daggregate=true -pl qacover-core -am
          -Dtest=ITTest* -DskipTests=true
          -Dsurefire.failIfNoSpecifiedTests=false
          -Dmaven.test.failure.ignore=true -U --no-transfer-progress

      # Reporting
      
      - name: Additional aggregated junit report
        if: always()
        uses: javiertuya/junit-report-action@v1.1.0
        with:
          surefire-files: "**/target/surefire-reports/TEST-*.xml"
          report-dir: target/site
          report-title: "Test Report: ${{ matrix.scope }} - Branch: ${{ github.ref_name }}"

      - name: Generate report checks
        if: always()
        uses: mikepenz/action-junit-report@v3.8.0
        with:
          check_name: "test-result-${{ matrix.scope }}"
          report_paths: "**/surefire-reports/TEST-*.xml"
          fail_on_failure: 'true'

      - if: always()
        name: Set unique jacoco.xml file names for each scope
        #if not sonarqube will overwrite al jacoco files generated for the same module but different scopes
        run: |
          for file in */target/site/jacoco/jacoco.xml ; do mv $file ${file//jacoco.xml/jacoco-${{ matrix.scope }}.xml} ; done
          ls -la */target/site/jacoco/*.xml

      - name: Publish test report files
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: "test-report-files-${{ matrix.scope }}"
          path: |
            target/site
            **/target/site/jacoco/jacoco*.xml
            **/target/surefire-reports
            **/target/failsafe-reports
            **/target/*.html
            **/target/*.log

  test-net:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: net
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-dotnet@v3.2.0
        with:
            dotnet-version: '6.0.x'

      - name: Launch Sqlserver
        run: |
          docker stop test-sqlserver && docker rm test-sqlserver
          docker run -d -p 1433:1433 --name test-sqlserver  --restart unless-stopped \
            -e SA_PASSWORD="$TEST_SQLSERVER_PWD" \
            -e TEST_SQLSERVER_PWD="$TEST_SQLSERVER_PWD" \
            -e "ACCEPT_EULA=Y" -e "MSSQL_PID=Developer" \
            -v ${GITHUB_WORKSPACE}/setup/sqlserver:/setup.d \
            mcr.microsoft.com/mssql/server:2017-latest
          chmod u+x ../setup/wait-container-ready.sh && ../setup/wait-container-ready.sh test-sqlserver "SQL Server is now ready for client connections"
          # SQLServer does not have an on startup script, run it now
          docker exec test-sqlserver bash -c "chmod u+x setup.d/sqlserver-setup.sh && ./setup.d/sqlserver-setup.sh"     
      
      - name: Run test - ADO.NET
        run: dotnet test --logger "trx;LogFileName=../../reports/qacover-report.trx" QACoverTest/QACoverTest.csproj
      - name: Junit html report - ADO.NET
        if: always()
        uses: javiertuya/junit-report-action@v1.1.0
        with:
          net-trx-report: "net/reports/qacover-report.trx"
          net-surefire-folder: "net/target/surefire-reports"
          surefire-files: "net/target/surefire-reports/TEST-*.xml"
          report-dir: net/target/site
          report-title: "Test Report: Net - Branch: ${{ github.ref_name }}"

      #- name: Run test - Entity Framework
      #  run: dotnet test --logger "trx;LogFileName=../../reports/qacover-report-ef.trx" QACoverTestEf/QACoverTestEf.csproj
      #- name: Junit html report - Entity Framework
      #  if: always()
      #  uses: javiertuya/junit-report-action@v1.1.0
      #  with:
      #    net-trx-report: "net/reports/qacover-report-ef.trx"
      #    net-surefire-folder: "net/target/surefire-reports"
      #    surefire-files: "net/target/surefire-reports/TEST-*.xml"
      #    report-dir: net/target/site
      #    report-title: "Test Report: Net - Branch: ${{ github.ref_name }}"
        
      - name: Generate report checks
        if: always()
        uses: mikepenz/action-junit-report@v3.8.0
        with:
          check_name: "test-result-Net"
          report_paths: "net/surefire-reports/TEST-*.xml"
          fail_on_failure: 'true'

      - name: Publish test report files
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: "test-report-files-Net"
          path: |
            net/target/site
            net/target/surefire-reports
            net/reports/qacover-report*.trx
            net/reports/*.html
            net/reports/*.log

      # As a last step, checks that conversion works to detect potential incompatible changes in the java side.
      # Note that updates on the java side are still made in the develop environment and pushed.
      - name: Validate Sharpen Conversion - Prepare Java envrionment
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '8'
          cache: 'maven'
      - name: Validate Sharpen Conversion - Preprocess
        if: always()
        run: |
          mvn -f ../pom.xml generate-sources -am
          ant clean sharpen.preprocess
      - name: Validate Sharpen Conversion - Sharpen
        if: always()
        uses: javiertuya/sharpen-action@v1.1.0
        with:
          working-dir: net
          project-dir: sharpen-temp/java
          sharpen-args: '@sharpen-all-options.txt'
      - name: Validate Sharpen Conversion - Postprocess
        if: always()
        run: |
          ls -la sharpen-temp/sharpen-temp.net
          sudo chown -R $(id -u):$(id -g) sharpen-temp/sharpen-temp.net
          ant sharpen.postprocess
          dotnet build
      
  sonarqube:
    needs: [test-java]
    #if: ${{ false }}  # disable for now
    #This job fails when comming from a dependabot PR (can't read the sonarqube token for security reasons).
    #Links to discussions and workaround at: https://github.com/giis-uniovi/samples-giis-template/issues/4
    if: ${{ github.actor != 'dependabot[bot]' }}
    runs-on: ubuntu-latest
    steps:
      - uses: javiertuya/sonarqube-action@v1.1.0
        with: 
          github-token: ${{ secrets.GITHUB_TOKEN }}
          sonar-token: ${{ secrets.SONAR_TOKEN }}
          restore-artifact-name1: "test-report-files-UT"
          restore-artifact-name2: "test-report-files-IT"

  publish-java-snapshot:
    #if: ${{ false }}  # disable for now
    #avoid publishing PRs and dependabot branches
    if: ${{ github.event_name != 'pull_request' && !contains('/head/refs/dependabot/', github.ref) }}
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: javiertuya/branch-snapshots-action@v1.2.0
        with: 
          token: ${{ secrets.GITHUB_TOKEN }}
          java-version: '8'
          mvn-deploy-args: '-P publish-github -DskipTests=true -DskipITs=true -Dmaven.test.failure.ignore=false -Dsurefire.failIfNoSpecifiedTests=false -U --no-transfer-progress'
          delete-old-snapshots: true
          min-snapshots-to-keep: 8
          always-keep-regex: "\\d*\\.\\d*\\.\\d*-main-SNAPSHOT$"
